### ISSUE TITLE
Handling of Home Server with Private IP

### ISSUE THREAD

**Issue by mm28ajos** [matrix-org/matrix-user-verification-service#20]
**Describe the bug**
UVS not working if using private ip-range, e.g.. docker net, to contact matrix synapse home server.

**To Reproduce**
1. Deploy UVS and synapse with docker in the same docker net.
2. Set .env homeserver variable to point to docker net host name of synapse.
3. Run verification request to USV.

**Expected behavior**
USV contacts synapse by docker net and retrieves room result.

**Additional context**
If using the UVS only within your own network e.g. to allow jitsi prosody to authenticate matrix users to use jitsi, you do not have to expose the admin API of synapse outside your local network i.e. the admin API of synapse must only be accessible by the docker host but not e.g. by hosts on the internet behind a reverse proxy. However, this setup does not work with USV as home server domains, which resolve to private ip addresses, are not accepted by UVS. Removing the blacklisting of private ip ranges or allowing to switch of the check might be a solution?

**Comment by mm28ajos** [comment]
Added a pull request, refer to #22

**Comment by jaywink** [comment]
Closed via #22
