### ISSUE TITLE
isDomainBlacklisted function seems confusingly named

### ISSUE THREAD

**Issue by lampholder** [matrix-org/matrix-user-verification-service#21]
https://github.com/matrix-org/matrix-user-verification-service/blob/dddc364797f168a3dbd0c440d137346c2766c728/src/utils.js#L131

If I'm reading it correctly, it seems to check if IP addresses are blacklisted (rather than domains), and returns true if the domain doesn't resolve (which isn't the same thing as being blacklisted).

I could be reading it wrong though, I'm a horrible software developer :P 

At the moment though it seems like UVS generates some confusing error messages about blacklisted IPs when it just can't resolve the DNS.

**Comment by mm28ajos** [comment]
Adressed this in PR #22

**Comment by jaywink** [comment]
Closed via #22 - please reopen if the confusion is not addressed sufficiently.
