### ISSUE TITLE
User verified but room membership check failed. But user is listed in the room.

### ISSUE THREAD

**Issue by H3lpD3sk-H3r0** [matrix-org/matrix-user-verification-service#38]
**Description:**
I am getting an error in the UVS logs when trying to get information about a user's presence in a room:

```
{
  requestId: '8ded3f7a-a76d-4137-851d-02ce3610749f',
  level: 'info',
  message: 'POST /verify/user_in_room: {"matrix_server_name":"mymatrixserver.com","room_id":"!wdYOMKQfWgX7PNBtzJ:mymatrixserver.com","token":"<redacted>"}',
  timestamp: '2024-10-19T10:42:30.410Z'
}
{
  requestId: '8ded3f7a-a76d-4137-851d-02ce3610749f',
  level: 'error',
  message: 'Failed to make verify request: Invalid URL',
  timestamp: '2024-10-19T10:42:30.545Z'
}
{
  requestId: '8ded3f7a-a76d-4137-851d-02ce3610749f',
  level: 'info',
  message: 'User verified but room membership check failed.',
  timestamp: '2024-10-19T10:42:30.546Z'
}
```

Because of this, the Prosody module does not receive the data to create the conference.
To check the data received from UVS, I make a POST request for `/verify/user_in_room` via Postman:
```
{
  "matrix_server_name": "mymatrixserver.com",
  "room_id": "!wdYOMKQfWgX7PNBtzJ:mymatrixserver.com",
  "token": "neNhOAeVsOnnFziElJbbuqIU"
}
```

Response:
```
{
    "results": {
        "user": true,
        "room_membership": false
    },
    "user_id": "@testuser:mymatrixserver.com",
    "power_levels": null
}
```
As I understand it, the answer says that `testuser` has no room membership. But it doesn't.

To test it, I perform a GET request to `_synapse/admin/v1/rooms/!wdYOMKQfWgX7PNBtzJ:mymatrixserver.com/members`.
Response:
```
{
    "members": [
        "@muvs_test:mymatrixserver.com",
        "@testuser:mymatrixserver.com",
        "@testuser1:mymatrixserver.com",
    ],
    "total": 3
}
```
As you can see `testuser` is in the room.

It is not possible to get detailed information, because the variable UVS_LOG_LEVEL does not work. Setting the value “debug” does not change the content of the logs.
Can you please tell me if there is a solution to this problem? And where can I catch the inconsistency?

**Software:**
Matrix User Verification Service 3.0.0
Matrix Synapse: 1.116.0
Prosody Auth Matrix User Verification: v1.8.1
Docker version 27.3.1, build ce12230

**Comment by benbz** [comment]
That looks like the `UVS_HOMESERVER_URL` env var hasn't been set correctly to a URL (you'll also need `UVS_ACCESS_TOKEN` set to an admin access token for that homeserver as per https://github.com/matrix-org/matrix-user-verification-service/blob/master/README.md#configuration)

**Comment by H3lpD3sk-H3r0** [comment]
My configuration parameters: 

```
UVS_ACCESS_TOKEN=<TOKEN>
UVS_HOMESERVER_URL=https://matrix.mymatrixserver.com
UVS_LISTEN_ADDRESS=127.0.0.1
UVS_PORT=3000
UVS_LOG_LEVEL=debug
UVS_OPENID_VERIFY_SERVER_NAME=mymatrixserver.com
UVS_DISABLE_IP_BLACKLIST=true
```
My Matrix server is located at matrix.mymatrixserver.com.
The `UVS_ACCESS_TOKEN` parameter contains a valid token, as I used it to verify room requests via Postman. I have no doubt about that.

What's also interesting is that a query for `/verify/user` returns a valid response. But a request for ` /verify/user_in_room` does not.

**Comment by benbz** [comment]
`/verify/user` doesn't use `UVS_HOMESERVER_URL`. It does the standard matrix federation server discovery to get the homeserver URL (`/.well-known/matrix/server` and SRV lookups) based on the server name in the MXID of the user being verified. 

`/verify/user_in_room` can't do this, as it needs admin credentials to a specific homeserver, and so must use `UVS_HOMESERVER_URL` .

The mymatrixserver.com is `NXDOMAIN` and so naturally the [federation tester](https://federationtester.matrix.org/api/report?server_name=mymatrixserver.com) is not happy with it. Either you're obfuscating it, in which case don't do when you're asking for help or you've got a private DNS setup, in which case check that matrix.mymatrixserver.com correctly resolves inside the UVS container

**Comment by H3lpD3sk-H3r0** [comment]
Thanks for your help!
Problem solved.
My errors:
- Docker variables were not taken from the .env file. I set them in the command to start the container. 
- Access from the global network to the admin API was closed.

To be honest, the installation and configuration instructions are raw. I had to follow the breadcrumbs. Please do not take it personally :) There are things obvious only to experienced matrix administrators/developers. 
Thanks again.
P.S. yes I am hiding the address of the real server.

**Comment by benbz** [comment]
:+1: glad you've got it working.

The docs are indeed fairly raw but this is a niche project for a niche use-case
